# """
# This configuration allows to set system properties of Trace-Creator virtual
# guests provisioned by Vagrant.
#
# All guest attributes in this example are mandatory.
# """
---

- name: source
  # Select Vagrant guest virtual machine box.
  # You can search for boxes at https://atlas.hashicorp.com/search
  box: ubuntu/trusty64
  box_url: ubuntu/trusty64
  # Selected IP addresses should not exists in your current network
  ip: 10.0.0.2
  # Mask of the virtual private network
  mask: 255.255.255.0
  # Number of virtual CPUs
  cpu: 1
  # Size of main memory is in MB
  memory: 1024
  # Ansible playbook provision file (provisioned before bash)
  ansible: configuration/provision/ansible/source.yml
  # Ansible requirements file (to include external roles)
  ansible_requirements: null
  # Bash provision file
  bash: null
  # Indicate if run trace-creator capture script.
  # Only one guest can have capture set to "true"! The guest will be deployed as last.
  creator: true

- name: destination-1
  box: ubuntu/trusty64
  box_url: ubuntu/trusty64
  ip: 10.0.0.3
  mask: 255.255.255.0  
  cpu: 1
  memory: 1024
  ansible: configuration/provision/ansible/destination-1.yml
  ansible_requirements: configuration/provision/ansible/requirements.yml
  bash: configuration/provision/bash/destination-1.sh
  creator: false
